### ISSUE TITLE
Image uploader

### ISSUE THREAD

**Issue by debdiproy** [cleonixtechnologies/Travel-Portal#3]
Please show the images that are uploaded just under the browse button in the respective pages of category, city center and location name

Also please use a cross mark with every image so that users can delete the images and update.

Please give me an estimated time before doing the work.

**Comment by creating-bubai** [comment]
Tomorrow  4pm

**Comment by creating-bubai** [comment]
Travel admin panel page location name,location type and city center multiple image upload edit section image delete completed.
Please check.

**Comment by debdiproy** [comment]
Thanks
